steps:
 
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/agent-vertex-demo/movie-booking-engine:$COMMIT_SHA'
      - '.'

 
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/agent-vertex-demo/movie-booking-engine:$COMMIT_SHA'


images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/agent-vertex-demo/movie-booking-engine:$COMMIT_SHA'


options:
  logging: CLOUD_LOGGING_ONLY